require: rubocop-rspec

# Code
Lint/Void:
  Enabled: false
  
Style/Documentation:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Enabled: false

# Tests
RSpec/DescribeClass:
  Exclude:
    - "spec/**/*_spec.rb"

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

# Gemfile
Bundler/OrderedGems:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
